[workspace]
members = [
	"crates/pcl_rustic_pybind",
	"crates/pcl_rustic_core",
	"crates/pcl_rustic_io",
	"crates/pcl_rustic_downsample",
]

# Legacy single-crate settings have been moved to Cargo.package.toml for reference.