[project]
name = "pcl-rustic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "liuzhen19", email = "liuzhen19@xiaomi.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pcl-rustic = "pcl_rustic:main"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "pcl_rustic._core" # python module name
python-packages = ["pcl_rustic"]
python-source = "python"
manifest-path = "crates/pcl_rustic_pybind/Cargo.toml"


[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "crates/**/*.rs" }, { file = "crates/**/Cargo.toml" }, { file = "Cargo.lock" },]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
